Develop
mate-academy/py-taxi-service-startproject pull request #123
Opened 2022-10-28 05:34 UTC by AVyha

![image](https://user-images.githubusercontent.com/80789163/198510496-36bd87d8-5c33-4e6b-8c21-f171c52f4de9.png)
![image](https://user-images.githubusercontent.com/80789163/198510563-8620c6d4-2093-48fb-aa5b-8da5f0f19806.png)
![image](https://user-images.githubusercontent.com/80789163/198510594-bcff2b10-8297-4719-8112-46f48c82a86c.png)
![image](https://user-images.githubusercontent.com/80789163/198510635-6a6ca885-fbe1-43b5-b4ff-0ccd4db3bb94.png)
![image](https://user-images.githubusercontent.com/80789163/198510654-4396c2b8-9399-4780-b6eb-e3a63bae4dc9.png)
![image](https://user-images.githubusercontent.com/80789163/198510673-7a943255-f008-402c-9463-731b248c3fd0.png)
![image](https://user-images.githubusercontent.com/80789163/198510688-a70b09dd-559d-43b5-98cd-45bdb18cfc12.png)

2022-10-31 07:16 UTC, HStakhiv requested changes
Use `black` to fix single quotes

2022-10-31 07:16 UTC, HStakhiv commented on taxi/models.py
> +        "Driver"
I think there should be an `AUTH_USER_MODEL` instead of `Driver`

2022-10-31 10:01 UTC, AVyha commented
> Why did not download the migration?
Im forget about migrations :)

2022-10-31 10:02 UTC, HStakhiv approved these changes
Looks good

2022-11-01 07:36 UTC, Y-Havryliv requested changes

2022-11-01 07:36 UTC, Y-Havryliv commented on .gitignore
> +.idea
add blank line to the end of the file

2022-11-02 08:21 UTC, Y-Havryliv approved these changes
GJ!

2024-12-01 14:29 UTC, closed without merging