'Solution'
mate-academy/py-taxi-service-startproject pull request #157
Opened 2022-11-01 16:10 UTC by davidkrivko

![4](https://user-images.githubusercontent.com/110781898/199281336-02816e60-c683-4b99-bd4f-c3b6b1e52dc5.png)
![3](https://user-images.githubusercontent.com/110781898/199281343-f9734dc8-3e3c-483f-a7d6-40704b48a7b8.png)
![2](https://user-images.githubusercontent.com/110781898/199281345-fafbf2dd-c423-4e3e-8486-039779e05123.png)
![1](https://user-images.githubusercontent.com/110781898/199281347-1d9e3d17-2d72-4af1-b9ed-e47c98c7cf79.png)

2022-11-02 09:49 UTC, IvanRamyk requested changes
please, write solution and don't delete workflow :))

2022-11-02 10:09 UTC, davidkrivko commented
> please, write solution and don't delete workflow :))

I didn't understand, what you mean

2022-11-03 08:39 UTC, IvanRamyk requested changes
do not delete the workflow and please, add a solution

2022-11-04 14:46 UTC, IvanRamyk requested changes
do not delete workflow

2022-11-04 23:17 UTC, davidkrivko commented
> do not delete workflow

I do not understand

2022-11-07 08:41 UTC, DmytroSvirsa requested changes
you had deleted the workflows folder
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/104418771/200264369-7c8939f3-f5be-4428-b638-b06e4fe36721.png">
bring it back

2022-11-07 10:02 UTC, DmytroSvirsa approved these changes

2026-03-01 02:00 UTC, closed without merging