Taxi service startproject solution
mate-academy/py-taxi-service-startproject pull request #530
Opened 2023-11-07 19:46 UTC by mwellick

2023-11-07 19:47 UTC, mwellick commented
![Знімок екрана (437)](https://github.com/mate-academy/py-taxi-service-startproject/assets/130235310/53e2d40a-2e08-4424-a96b-3da2208f6208)
![Знімок екрана (438)](https://github.com/mate-academy/py-taxi-service-startproject/assets/130235310/86bf43d8-9308-4c77-8548-7c04e25d4315)
![Знімок екрана (439)](https://github.com/mate-academy/py-taxi-service-startproject/assets/130235310/8c56e234-1b75-4920-85ed-b5b153b94501)
![Знімок екрана (440)](https://github.com/mate-academy/py-taxi-service-startproject/assets/130235310/d67be1de-2bc1-4828-b831-30bb033ac342)

2023-11-08 09:45 UTC, EdAlekseiev requested changes
Add `__pycache__` folder to `.gitignore` and delete them from repository

2023-11-08 11:20 UTC, ArsenPidhoretskyi requested changes

2023-11-08 11:20 UTC, ArsenPidhoretskyi commented on .gitignore
> +*.sqlite3
Add empty line

2023-11-08 11:51 UTC, ArsenPidhoretskyi approved these changes
Well done!

2025-07-25 12:22 UTC, closed without merging