Solution
mate-academy/py-taxi-service-startproject pull request #553
Opened 2023-11-13 14:47 UTC by YuliaHladyshkevych

<img width="1440" alt="Screenshot 2023-11-13 at 16 40 35" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/89917235/61c5f2dd-bc0f-405f-a9e8-77a932aae188">
<img width="1438" alt="Screenshot at Nov 13 16-32-07" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/89917235/1f8bfeb8-2fab-4ae3-951f-88a56354b224">
<img width="1439" alt="Screenshot at Nov 13 16-37-25" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/89917235/81c9ae6c-e1d6-4373-bdde-eba139438236">
<img width="1436" alt="Screenshot at Nov 13 16-44-56" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/89917235/7580bab5-947e-4789-9b09-f980b55599c9">
<img width="1105" alt="Screenshot at Nov 13 16-44-25" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/89917235/9726b47b-3741-435a-a8b5-ac2bd5bb783d">

2023-11-13 15:49 UTC, OlehShumov approved these changes

2023-11-15 13:07 UTC, fsocie7y requested changes

2023-11-15 13:07 UTC, fsocie7y commented on taxi/models.py
> +    drivers = models.ManyToManyField(AUTH_USER_MODEL)
add related name for Car model)
dont forget about [checklist.md](https://github.com/mate-academy/py-taxi-service-startproject/blob/master/checklist.md)

2023-11-15 13:07 UTC, fsocie7y commented on .gitignore
> +**db.sqlite3
add blank line to end of file

2023-11-15 13:40 UTC, fsocie7y approved these changes
well done ^_^

2024-09-20 14:23 UTC, closed without merging