taxi startproject
mate-academy/py-taxi-service-startproject pull request #582
Opened 2023-12-01 19:24 UTC by sbilikepy

2023-12-01 19:46 UTC, sbilikepy commented
http://127.0.0.1:8000/admin/
![image](https://github.com/mate-academy/py-taxi-service-startproject/assets/109094572/5f3ed07c-e060-430d-919c-389d255b3368)

http://127.0.0.1:8000/admin/taxi/driver/ - `license_number` displayed as the other fields
![image](https://github.com/mate-academy/py-taxi-service-startproject/assets/109094572/d750b2f9-3f64-40bd-9fbd-87aa06646102)

http://127.0.0.1:8000/admin/taxi/driver/2/change/ - `license_number` in the `fieldsets`
![image](https://github.com/mate-academy/py-taxi-service-startproject/assets/109094572/de4d1161-a597-40c5-be2e-0e897f4ff991)

http://127.0.0.1:8000/admin/taxi/driver/add/  - license_number in the `add_fieldset`
![image](https://github.com/mate-academy/py-taxi-service-startproject/assets/109094572/f0a28525-acb1-456c-a3a6-1ed4491a7483)

http://127.0.0.1:8000/admin/taxi/car/?q=911 - possibility to search a `Car `by `model`
![image](https://github.com/mate-academy/py-taxi-service-startproject/assets/109094572/4fa603ab-5244-45be-af0c-e139fdfeada1)

http://127.0.0.1:8000/admin/taxi/car/ - possibility to filter `Car `by `manufacturer`
![image](https://github.com/mate-academy/py-taxi-service-startproject/assets/109094572/818fcf9c-72b6-472e-a296-45a38f10708d)

2023-12-01 19:58 UTC, vsmutok requested changes
Please  fix tests

2023-12-01 21:02 UTC, sbilikepy commented
I asked about test in py_1chat on platform, need some help

2023-12-02 16:47 UTC, vsmutok requested changes
Please  remove .idea from PR

2023-12-03 11:47 UTC, vasylhnatiuk approved these changes

2026-07-30 15:20 UTC, closed without merging