First commit. Created project and taxi app, costumized admin panel, c…
mate-academy/py-taxi-service-startproject pull request #591
Opened 2023-12-10 18:15 UTC by rurakite

<img width="1440" alt="Admin Panel" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/107404981/d7e6f65e-1b70-43cb-946d-4bfcfa7c7a10">

2023-12-10 20:21 UTC, YukihiroSM requested changes
Please, add screenshots of cars, drivers and manufacturers admin pages and add some instances to the project, so the structure can be vissible

2023-12-11 11:59 UTC, ArsenPidhoretskyi requested changes
Check your code for flake8 also

2023-12-11 11:59 UTC, ArsenPidhoretskyi commented on .gitignore
> +db.sqlite3
Add an empty line.
Each file must end empty line

2023-12-11 12:41 UTC, EdAlekseiev approved these changes
Good job

2026-03-24 21:09 UTC, closed without merging