need help with additional info assertation, can't find the source of …
mate-academy/py-taxi-service-startproject pull request #611
Opened 2024-01-05 14:04 UTC by VladyslavShepilov

…an issue

2024-01-05 14:14 UTC, vasylhnatiuk requested changes
fix tests

2024-01-07 21:25 UTC, VladyslavShepilov commented
<img width="1512" alt="Снимок экрана 2024-01-07 в 23 24 21" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/136336159/91a93d41-7418-47c4-9980-95f197a09271">
<img width="1512" alt="Снимок экрана 2024-01-07 в 23 24 27" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/136336159/a027f908-c7f3-4d95-a59a-0d9cbb18e743">
<img width="1512" alt="Снимок экрана 2024-01-07 в 23 24 32" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/136336159/4660d8d2-0c51-474a-ab62-e266aae2cf4c">
<img width="1512" alt="Снимок экрана 2024-01-07 в 23 24 13" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/136336159/6cbad99a-3fb7-42da-a000-425e21391e5d">
<img width="1512" alt="Снимок экрана 2024-01-07 в 23 23 40" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/136336159/e57fddea-7658-4810-bb6d-a1f4e4b5d316">
<img width="1512" alt="Снимок экрана 2024-01-07 в 23 23 36" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/136336159/7c45fdd2-03a7-46d5-a0e5-e545ab8fe21f">

2024-01-07 21:28 UTC, VladyslavShepilov commented
<img width="1512" alt="Снимок экрана 2024-01-07 в 23 27 23" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/136336159/ce84910e-521a-43a3-8263-68d0e152c5ea">
<img width="1512" alt="Снимок экрана 2024-01-07 в 23 27 16" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/136336159/92216884-0a81-4038-b036-4e7d0fc5b1ec">
<img width="1512" alt="Снимок экрана 2024-01-07 в 23 27 26" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/136336159/2ed75270-ab95-43ce-840d-717f837832ba">
<img width="1512" alt="Снимок экрана 2024-01-07 в 23 27 10" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/136336159/2d53168c-1ff4-4c17-bef8-71fe27042868">
<img width="1512" alt="Снимок экрана 2024-01-07 в 23 27 06" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/136336159/e8dd94e1-04d4-4a45-8058-cafd5b0ac863">
<img width="1512" alt="Снимок экрана 2024-01-07 в 23 27 28" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/136336159/92f89c22-dab8-4d86-b67f-ebe874291105">

2024-01-07 21:31 UTC, VladyslavShepilov commented
<img width="1512" alt="Снимок экрана 2024-01-07 в 23 27 28" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/136336159/9af531a2-d3ee-4e04-b187-bc91e923d2f5">

2024-01-08 10:01 UTC, ArsenPidhoretskyi requested changes
Remove pycache from github. Read about git rm --cached

2024-01-08 14:50 UTC, vasylhnatiuk requested changes
![зображення](https://github.com/mate-academy/py-taxi-service-startproject/assets/104974881/bdfcb69f-4781-4117-8362-926b541eeb70)
remove it also

2024-01-08 19:51 UTC, vsmutok approved these changes
well done!

2025-10-24 20:37 UTC, closed without merging