'solution'
mate-academy/py-taxi-service-startproject pull request #727
Opened 2024-04-11 18:01 UTC by xborismenx

![1](https://github.com/mate-academy/py-taxi-service-startproject/assets/116746895/39519808-fb10-4034-a4bb-75e0e3a02841)
![2](https://github.com/mate-academy/py-taxi-service-startproject/assets/116746895/e28b4816-23c8-450b-8e6f-1b6f9dc82c4e)
![3](https://github.com/mate-academy/py-taxi-service-startproject/assets/116746895/58d37712-87db-49fc-9f28-57fe6b782a89)
![4](https://github.com/mate-academy/py-taxi-service-startproject/assets/116746895/555bce45-1dc8-43b1-a6af-1031509f489d)
![5](https://github.com/mate-academy/py-taxi-service-startproject/assets/116746895/cbc554d8-51cc-4c30-bced-d7ce08c54b28)

2024-04-11 18:52 UTC, EdAlekseiev requested changes

2024-04-11 18:52 UTC, EdAlekseiev commented on .gitignore
> +.pyc
Add empty line

2024-04-11 18:52 UTC, EdAlekseiev commented on taxi_service/__pycache__/__init__.cpython-310.pyc
Delete __pycache__ folder and add to .gitignore

2024-04-12 05:21 UTC, vsmutok requested changes
please remove `taxi_service/__pycache__/` from PR

![image](https://github.com/mate-academy/py-taxi-service-startproject/assets/93856423/1935d093-ed63-4e3c-af4e-cdd46a5257f5)

2024-04-12 18:00 UTC, EdAlekseiev requested changes
Delete `__pycache__` folder and add it to .gitignore file

2024-04-13 15:15 UTC, ArsenPidhoretskyi approved these changes
Well done!

2026-02-23 07:51 UTC, closed without merging