done
mate-academy/py-taxi-service-startproject pull request #758
Opened 2024-05-04 16:23 UTC by antonver

2024-05-04 16:36 UTC, antonver commented
<img width="1431" alt="Снимок экрана 2024-05-04 в 18 35 48" src="https://github.com/mate-academy/py-taxi-service-startproject/assets/41055946/bbf8b2bf-3959-4f39-8d50-30b65d1e2835">
I wanted to ask why I do not have Driverse, but have users

2024-05-04 17:51 UTC, vsmutok requested changes
Please remove `db.sqlite3` and `.idea` from PR

2024-05-06 13:56 UTC, Polyakiv-Andrey requested changes

2024-05-06 13:56 UTC, Polyakiv-Andrey commented on taxi/models.py
> +class Manufacturer(models.Model):
add str method for model

2024-05-06 13:56 UTC, Polyakiv-Andrey commented on taxi/models.py
> +class Driver(AbstractUser):
add str method for model

2024-05-06 13:56 UTC, Polyakiv-Andrey commented on taxi/models.py
> +class Car(models.Model):
add str method for model

2024-05-06 13:56 UTC, Polyakiv-Andrey commented on taxi/__init__.py
delete all pyc files from git

2024-05-07 14:53 UTC, closed without merging